### ISSUE TITLE
Unable to use Lipika on MacOS 10.15.7

### ISSUE THREAD

**Issue by trivedigaurav** [ratreya/lipika-ime#57] opened 2020-10-26 18:21 UTC
**Describe the bug**
Switching to Lipika shows an error message on MacOS 10.15.7 with text that "LipikaIME"  will damage your computer.

**To Reproduce**
1. Install Lipika from the [provided installer](https://github.com/ratreya/lipika-ime/releases/download/2.2/LipikaIME.pkg)
2. Follow the instructions on the [wiki](https://github.com/ratreya/lipika-ime/wiki) to install.
3. See error upon switching input source.

**Screenshots**
<img width="542" alt="Screen Shot 2020-10-26 at 2 15 50 PM" src="https://user-images.githubusercontent.com/377867/97212205-6f9c9c80-1796-11eb-97fe-22f191f66e25.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Version: 2.2

**Comment by ratreya** [comment] 2020-11-18 18:24
I tried a clean install on the same OS version but I am unable to reproduce the issue. If possible, can you please also provide log statements from Console App around the time when this happens?

**Comment by chtnha** [comment] 2020-11-20 10:18
I am using the same version of Mac OS Catalina - 10.15.7 and installed Lipika and now I am able to write Kannada using ITRANS.

**Comment by ratreya** [comment] 2020-11-29 01:40
Please provide crash logs from Console App if possible. Without logs, it is impossible to debug because this issue is not reproducible.

**Comment by trivedigaurav** [comment] 2020-11-29 02:42
I tried again, it seems to be working fine now. Not sure what was the issue
before.

**Comment by ratreya** [comment] 2020-11-30 01:49
Thanks for confirming. Closing as no-repro.

**Closed by ratreya** 2020-11-30 01:49 UTC
Labels: bug, norepro

**Comment by trivedigaurav** [comment] 2020-11-30 05:04
I am seeing a new issue now. Maybe this is related to why I had the issue
in the first place.

I had deleted the files from /Library/Input\ Methods/LipikaIME.app/ to try
a fresh install. However, I don't see Schemes/Google in /Library/Input\
Methods/LipikaIME.app/ any longer. Is that normal?

Also, https://github.com/ratreya/google-ime-scm linked in
https://github.com/ratreya/lipika-ime/wiki#transliteration-schemes no
longer exists.

**Comment by ratreya** [comment] 2020-12-03 06:01
Google custom scheme support [has been deprecated](https://www.facebook.com/groups/lipika.ime/permalink/2545467212385753/). You can use LipikaApp which also gets installed with LipikaIME to configure your mappings. You can also export and import mappings if you need to share it with others.
